aws_region="us-east-2"
env="prod"
bikeshare_scored_data_storage="bikeshare-scored-data"
prefect_artifacts_scoring_storage="prefect-flows-zoomcamp-project-scoring"
prefect_artifacts_training_monitoring_storage="prefect-flows-zoomcamp-project-model"
mlflow_backend_storage="bikeshare-model-artifacts"